'use strict'

const generateASS = (video, framesData) => {

    console.log("START GENERATE");
    console.log(framesData);

    console.log(video.offsetWidth);
    console.log(video.offsetHeight);

    const videoOffsetX = video.offsetWidth / 2;
    const videoOffsetY = video.offsetHeight / 2;
    const proportionX = video.videoWidth / video.offsetWidth;
    const proportionY = video.videoHeight / video.offsetHeight;

    const assBeginning = `[Script Info]\n
    ; Script generated by ASS Animation\n
    ; www.github.com/JestAK/ass-animation\n
    ScriptType: v4.00+\n
    PlayResX: ${video.videoWidth}\n
    PlayResY: ${video.videoHeight}\n
    WrapStyle: 2\n\n
    [V4+ Styles]\n
    Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\n
    Style: ASS Animation,Arial,20,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,1,0,0,0,100,100,0,0,1,2,0,2,10,10,10,1\n\n
    [Events]\n
    Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text`;
    console.log("FINISH GENERATE INFO");

    const dialogues = framesData.map(data => {
        console.log("CREATING DIALOGUE");
        if (data.opacity !== 255){
            return `Dialogue: 0,${data.startTime},${data.endTime},ASS Animation,Animation ID${data.id},0,0,0,,{\\pos(${(data.posX + videoOffsetX) * proportionX},${(data.posY + videoOffsetY + data.fontSize/2) * proportionY})\\fs${data.fontSize * proportionY}\\fscx${data.scaleX * 100}\\fscy${data.scaleY * 100}\\frz${data.rotateZ}\\frx${data.rotateX}\\fry${data.rotateY}\\c&H${data.textColor}\\3c&H${data.strokeColor}&\\bord${data.strokeThickness}\\1a&H${data.opacity}&\\2a&H${data.opacity}&\\3a&H${data.opacity}&\\4a&H${data.opacity}&}${data.content}`;
        }
        return "";
    });

    const result = assBeginning + dialogues.join("\n");
    return new Blob([result], {type: 'text/plain'});
}

export default generateASS;


